(()=>{'use strict';
const base='agentic/decision_evidence/', names={S:'末端位姿和夹爪宽度',J:'手臂关节角度与速度',K:'相机几何标定',F:'上一动作实际到达误差',H:'过去两轮图像与自身动作'},cam={head_camera:'头部',chest_camera:'胸部',third_camera:'第三视角',wrist_camera:'腕部'},fr3cam={head_camera:'近景',chest_camera:'全景',third_camera:'俯视',wrist_camera:'腕部'};
const labels={status:'执行状态',stop_reason:'终止或拒绝原因',feedback:'执行后反馈（不是本轮输入）',static_robot:'静态机器人与手先验',sim_time_s:'仿真时刻（秒）',hand_joint_limits_rad:'主动手关节范围（弧度）',arm_joint_limits_rad:'手臂关节范围（弧度）',position_world_m:'世界坐标位置（米）',quaternion_world_wxyz:'世界朝向四元数（w,x,y,z）',robot_base_position_world_m:'基座世界位置（米）',robot_base_quaternion_world_wxyz:'基座朝向四元数',gripper_width_m:'夹爪宽度（米）',arm_joint_position_rad:'7 个关节角度（弧度）',arm_joint_velocity_rad_s:'7 个关节速度（弧度/秒）',delta_position_wrist_m:'手腕坐标系位置变化（米）',delta_rotation_wrist_rotvec_rad:'手腕坐标系旋转向量（弧度）',duration_s:'动作时长（秒）',position_error_m:'位置到达误差（米）',orientation_error_rad:'朝向到达误差（弧度）',requested_duration_s:'请求时长（秒）',executed_duration_s:'实际执行时长（秒）',K_pixels:'相机内参（像素）',T_world_from_camera_opencv:'相机到世界坐标变换',memory_from_previous_decision:'模型上一轮留下的文字记忆',last_action_status:'上一动作类别反馈',visual_observation:'模型对图像的描述',memory_for_next_observation:'模型留给下一轮的文字记忆',task_done:'模型声明任务完成',actions:'请求动作',waypoints:'世界坐标路点',robot:'机器人实时数值状态',cameras:'相机标定',hand_joint_position_rad:'六维主动手关节角度（弧度）',hand_joint_velocity_rad_s:'六维主动手关节速度（弧度/秒）',hand_semantics:'手部关节语义',last_execution_feedback:'上一动作执行反馈',task_instruction:'任务说明',requests_remaining_including_this:'本轮起剩余请求次数'};
function el(t,txt,cls){const n=document.createElement(t);if(txt!==undefined)n.textContent=txt;if(cls)n.className=cls;return n;}
function value(v){if(typeof v==='number')return Number(v.toPrecision(6));if(v===null)return '暂无记录';if(Array.isArray(v)&&v.every(x=>typeof x!=='object'))return '['+v.map(value).join(', ')+']';return typeof v==='object'?JSON.stringify(v,null,2):String(v);}
function fields(v){const box=el('dl',undefined,'step-fields');for(const[k,x]of Object.entries(v||{})){box.append(el('dt',labels[k]||k));const d=el('dd');d.append(el('pre',value(x)));box.append(d);}return box;}
function fold(title,v){const d=el('details');d.append(el('summary',title),fields(v));return d;}
let manifestPromise;function manifest(){return manifestPromise||(manifestPromise=fetch(base+'manifest.json').then(r=>{if(!r.ok)throw Error('manifest');return r.json();}));}
function attach(host,getId,eventName){if(!host)return;const box=el('section',undefined,'step-viewer'),disclosure=el('details',undefined,'step-disclosure');disclosure.append(el('summary','逐轮查看：四张实际输入图、模型状态与动作'),box);host.append(disclosure);let active=false,seq=0,abort,episode,index=0;
async function load(){if(!active)return;const ticket=++seq;abort?.abort();abort=new AbortController();box.replaceChildren(el('p','正在加载所选试验的逐轮记录…'));try{const m=await manifest(),entry=m.episodes.find(x=>x.episode_id===getId());if(!entry)throw Error('本条逐轮证据尚未提供');const r=await fetch(base+entry.file,{signal:abort.signal});if(!r.ok)throw Error('记录加载失败');const e=await r.json();if(ticket!==seq)return;episode=e;index=0;render();}catch(err){if(ticket===seq&&err.name!=='AbortError')box.replaceChildren(el('p','逐轮记录暂不可用：'+err.message));}}
function render(){const cameraNames=episode.robot==='Franka FR3'?fr3cam:cam;const d=episode.decisions[index];box.replaceChildren(el('h4','逐轮看：当时给了模型什么？'));if(!d){box.append(el('p','没有可用的决策记录。'));return;}
const controls=el('div',undefined,'step-controls'),prev=el('button','上一步'),next=el('button','下一步'),select=el('select');select.setAttribute('aria-label','选择模型决策轮次');episode.decisions.forEach((x,i)=>{const o=el('option',x.title_zh||'第 '+x.decision_number+' 轮');o.value=i;select.append(o);});select.value=index;prev.disabled=index===0;next.disabled=index===episode.decisions.length-1;prev.onclick=()=>{index--;render();};next.onclick=()=>{index++;render();};select.onchange=()=>{index=Number(select.value);render();};controls.append(prev,select,next);box.append(controls);
box.append(el('p','以下是这一轮实际请求的 RGB 原图，不是从录像截取，也不是事后重渲染。点击图片可查看原图。','step-note'));
const imgs=d.image_evidence||[],current=imgs.filter(x=>x.temporal_role==='current'||(!x.temporal_role&&!/PREVIOUS|HISTORY/i.test(x.label))),grid=el('div',undefined,'step-images');for(const key of Object.keys(cam)){const item=current.find(x=>x.camera===key||x.label?.includes(key)),fig=el('figure');fig.append(el('figcaption',cameraNames[key]));if(item?.url){const a=el('a'),img=el('img');a.href=base+item.url;a.target='_blank';a.rel='noopener';img.src=a.href;img.loading='lazy';img.decoding='async';img.alt=episode.robot+' 第'+d.decision_number+'轮 '+cameraNames[key]+'实际输入';a.append(img);fig.append(a);}else fig.append(el('p','原图缺失：'+(item?.missing_reason||'未提供对应图像')));grid.append(fig);}box.append(grid);
const p=d.policy_observation||{},groups=d.mask_metadata?.groups||episode.mask_metadata?.groups||{};box.append(el('h5','本轮模型可见的数值与历史'));if(['S','J','K','F'].some(k=>k in p)||episode.robot==='Franka FR3'){
for(const[k,title]of Object.entries(names)){const heading=episode.robot==='Franka FR3'?title:(k==='S'?'末端与基座位姿':k==='J'?'手臂与主动手关节状态':title);const v=k==='H'?p.previous_observations_own_actions:p[k];const removed=(d.mask_metadata||episode.mask_metadata)?groups[k]?.status==='removed_by_condition':episode.robot==='Franka FR3'&&(episode.condition==='rgb_only'||episode.condition==='minus_'+k);const empty=v===null||v===undefined||(Array.isArray(v)&&!v.length);if(removed)box.append(el('p',heading+'：本条件未提供。','step-mask'));else if(empty)box.append(el('p',heading+'：'+(k==='F'?'本轮尚无上一动作反馈。':k==='H'?'本轮尚无过去决策记录。':'本轮无可用记录。')));else if(k==='S'||k==='J'){const section=el('div',undefined,'step-state');section.append(el('strong',heading),fields(v));box.append(section);}else box.append(fold(heading+(k==='H'?'（'+v.length+' 轮）':''),v));}
const common={};for(const k of ['task_instruction','requests_remaining_including_this','memory_from_previous_decision','last_action_status'])if(k in p)common[k]=p[k];box.append(fold('共同文字信息与模型自写记忆',common));if(p.static_robot)box.append(fold('静态机器人与六维手先验',p.static_robot));
}else {if(p.robot){const brief=el('div',undefined,'step-state');brief.append(el('strong','实际腕部与关节状态'),fields(Object.fromEntries(Object.entries(p.robot).filter(([k])=>['position_world_m','quaternion_world_wxyz','arm_joint_position_rad','arm_joint_velocity_rad_s','hand_joint_position_rad','hand_joint_velocity_rad_s'].includes(k)))));box.append(brief);}for(const[k,v]of Object.entries(p))box.append(fold(d.mask_metadata?.field_groups_zh?.[k]||labels[k]||k,typeof v==='object'&&v!==null?v:{value:v}));}
const historical=imgs.filter(x=>!current.includes(x));if(historical.length){const hist=el('details');hist.append(el('summary','查看这轮同时送入的 '+historical.length+' 张历史图'));hist.addEventListener('toggle',()=>{if(!hist.open||hist.dataset.loaded)return;hist.dataset.loaded='1';const g=el('div',undefined,'step-images');for(const item of historical){const fig=el('figure');fig.append(el('figcaption','历史观察 '+item.observation_index+' · '+(cameraNames[item.camera]||item.label)));if(item.url){const a=el('a'),im=el('img');a.href=base+item.url;a.target='_blank';a.rel='noopener';im.src=a.href;im.loading='lazy';im.alt='实际送入的历史图';a.append(im);fig.append(a);}else fig.append(el('p',item.missing_reason||'原图缺失'));g.append(fig);}hist.append(g);});box.append(hist);}box.append(el('p','这轮记录含当前图 '+current.length+' 张、历史输入图 '+historical.length+' 张。不给状态，指不把这些数值告诉模型；底层控制器仍读取关节状态执行动作。','step-note'));
box.append(el('h5','模型请求的动作'),el('p',episode.robot==='Franka FR3'?'位置与旋转变化使用手腕相对坐标；夹爪用宽度控制。':'本协议使用世界坐标末端目标与主动手关节角度；与 FR3 相对动作不同。'));
if(d.candidate){const actions=d.candidate.actions||d.candidate.waypoints; if(Array.isArray(actions))actions.forEach((a,i)=>{box.append(el('strong','动作 '+(i+1)),fields(a));});box.append(fold('模型完整输出（含原文观察和自写记忆）',d.candidate));}else box.append(el('p','本轮没有可用模型动作输出；如请求中断，不视为机器人动作失败。'));
box.append(fold('执行记录（执行之后产生，未必给模型）',{status:d.request_status,stop_reason:d.request_stop_reason||d.episode_stop_reason_if_last,feedback:d.execution_feedback}));box.append(el('p','本轮请求等待 '+Number(d.call_elapsed_wall_s||0).toFixed(2)+' 秒；输入 '+(d.usage?.input_tokens??'未知')+' / 输出 '+(d.usage?.output_tokens??'未知')+' token；'+(d.usage_unknown?'费用未知（已知部分 $'+Number(d.known_standard_equivalent_usd||0).toFixed(5)+'）。':'已知等值 $'+Number(d.known_standard_equivalent_usd||0).toFixed(5)+'。'),'step-note'));
}
if(eventName)document.addEventListener(eventName,load);disclosure.addEventListener('toggle',()=>{active=disclosure.open;if(active)load();else{seq++;abort?.abort();box.replaceChildren();}});}
attach(document.querySelector('#psibot-new-input'),()=> 'psibot_input_9511_full');
attach(document.querySelector('#episode-player'),()=>`fr3_${document.querySelector('#seed-choice').value}_${document.querySelector('#condition-choice').value}`,'astra-fr3-episode');attach(document.querySelector('#psibot-history-playback'),()=>`psibot_e3_${document.querySelector('#psibot-episode-choice').value}`,'astra-psibot-episode');attach(document.querySelector('#long-regrasp-result'),()=> 'fr3_long1_minus_S_9403');
})();
